# Ciudades donde opera Tiendas Ara — validación automática en AraBot
# Clave: CIUDAD en mayúsculas, Valor: {departamento, zona, cod_reg}

CIUDADES = {
    "PEREIRA":{"departamento":"RISARALDA","zona":"OCCIDENTE","cod_reg":"R1"},
    "ARMENIA":{"departamento":"QUINDIO","zona":"OCCIDENTE","cod_reg":"R1"},
    "SANTA ROSA":{"departamento":"RISARALDA","zona":"OCCIDENTE","cod_reg":"R1"},
    "SANTA ROSA DE CABAL":{"departamento":"RISARALDA","zona":"OCCIDENTE","cod_reg":"R1"},
    "VILLA MARIA":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "ZARZAL":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "DOSQUEBRADAS":{"departamento":"RISARALDA","zona":"OCCIDENTE","cod_reg":"R1"},
    "TULUA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "CALARCA":{"departamento":"QUINDIO","zona":"OCCIDENTE","cod_reg":"R1"},
    "CARTAGO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "CHINCHINA":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "MANIZALES":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "MANIZALEZ":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "BUGA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "OBANDO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "LA VIRGINIA":{"departamento":"RISARALDA","zona":"OCCIDENTE","cod_reg":"R1"},
    "CAICEDONIA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "ANSERMA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "ANDALUCIA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "VITERBO":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "ALCALA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "TORO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "LA VICTORIA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "SEVILLA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "CIRCASIA":{"departamento":"QUINDIO","zona":"OCCIDENTE","cod_reg":"R1"},
    "NEIRA":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "FILANDIA":{"departamento":"QUINDIO","zona":"OCCIDENTE","cod_reg":"R1"},
    "QUIMBAYA":{"departamento":"QUINDIO","zona":"OCCIDENTE","cod_reg":"R1"},
    "BUGALAGRANDE":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "BELALCAZAR":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "SAN PEDRO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "MARSELLA":{"departamento":"RISARALDA","zona":"OCCIDENTE","cod_reg":"R1"},
    "LA UNION":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "MONTENEGRO":{"departamento":"QUINDIO","zona":"OCCIDENTE","cod_reg":"R1"},
    "LA TEBAIDA":{"departamento":"QUINDIO","zona":"OCCIDENTE","cod_reg":"R1"},
    "APIA":{"departamento":"RISARALDA","zona":"OCCIDENTE","cod_reg":"R1"},
    "BARCELONA":{"departamento":"QUINDIO","zona":"OCCIDENTE","cod_reg":"R1"},
    "RIOSUCIO":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "EL DOVIO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "ARANZAZU":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "SUPIA":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "ROLDANILLO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "TRUJILLO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "LA PAILA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R1"},
    "PALESTINA":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "BELEN DE UMBRIA":{"departamento":"RISARALDA","zona":"OCCIDENTE","cod_reg":"R1"},
    "SANTUARIO":{"departamento":"RISARALDA","zona":"OCCIDENTE","cod_reg":"R1"},
    "SALAMINA":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "QUINCHIA":{"departamento":"RISARALDA","zona":"OCCIDENTE","cod_reg":"R1"},
    "MANZANARES":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "PENSILVANIA":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "PACORA":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R1"},
    "SALENTO":{"departamento":"QUINDIO","zona":"OCCIDENTE","cod_reg":"R1"},
    "BARRANQUILLA":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "BARRRANQUILLA":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "ARJONA":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R2"},
    "CARTAGENA":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R2"},
    "GALAPA":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "MALAMBO":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "MARIA LA BAJA":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R2"},
    "PUERTO COLOMBIA":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "SAN JUAN NEPOMUCENO":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R2"},
    "SANTA MARTA":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R2"},
    "CALAMAR":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R2"},
    "SAN JACINTO":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R2"},
    "CARMEN DE BOLIVAR":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R2"},
    "OVEJAS":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "SABANAGRANDE":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "JUAN DE ACOSTA":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "MAGANGUE":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R6"},
    "SOLEDAD":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "CIENAGA":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R2"},
    "TURBACO":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R2"},
    "POLONUEVO":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "SANTO TOMAS":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "SABANALARGA":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "SINCELEJO":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "LURUACO":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "BARANOA":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "REPELON":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "PONEDERA":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "SANTA LUCIA":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "MANATI":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "PALMAR DE VARELA":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "CAMPO DE LA CRUZ":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "SUAN":{"departamento":"ATLANTICO","zona":"NORTE","cod_reg":"R2"},
    "PIVIJAY":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R2"},
    "FUNDACION":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R2"},
    "ARACATACA":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R2"},
    "ZONA BANANERA":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R2"},
    "ORIHUECA":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R2"},
    "EL RETEN":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R2"},
    "EL PIÑON":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R2"},
    "SITIONUEVO":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R2"},
    "PLATO":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R10"},
    "ARIGUANI":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R10"},
    "CHIBOLO":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R10"},
    "SANTA ANA":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R10"},
    "EL BANCO":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R10"},
    "NUEVA GRANADA":{"departamento":"MAGDALENA","zona":"NORTE","cod_reg":"R10"},
    "BOGOTA":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R4"},
    "BARRIOS UNIDOS":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R4"},
    "CHAPINERO":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R4"},
    "ENGATIVA":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R4"},
    "SANTA FE":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "PUENTE ARANDA":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "TUNJUELITO":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "FONTIBON":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R4"},
    "USME":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "SUBA":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R4"},
    "CIUDAD BOLIVAR":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "TEUSAQUILLO":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R4"},
    "USAQUEN":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R4"},
    "RAFAEL URIBE URIBE":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "SAN CRISTOBAL":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "KENNEDY":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "BOSA":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "LOS MARTIRES":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "ANTONIO NARIÑO":{"departamento":"BOGOTA","zona":"CENTRO","cod_reg":"R3"},
    "CHIA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "SOACHA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "SOACHA SAN MATEO":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "COTA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "FUNZA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "TABIO":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "VILLETA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "CAJICA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "MOSQUERA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "MADRID":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "SOPO":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "TOCANCIPA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "ZIPAQUIRA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "GACHANCIPA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "FACATATIVA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "SIBATE":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "FUSAGASUGA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "TOCAIMA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "PACHO":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "ANAPOIMA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "SUESCA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "LA CALERA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "TENJO":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "BOJACA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "VILLAPINZON":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "UBATE":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "CHOCONTA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "AGUA DE DIOS":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "GUASCA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "APULO":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "NEMOCON":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "EL COLEGIO":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "SUBACHOQUE":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "ANOLAIMA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "VIOTA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "PUERTO SALGAR":{"departamento":"CUNDINAMARCA","zona":"OCCIDENTE","cod_reg":"R7"},
    "GUADUAS":{"departamento":"CUNDINAMARCA","zona":"OCCIDENTE","cod_reg":"R7"},
    "GIRARDOT":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "FLANDES":{"departamento":"TOLIMA","zona":"CENTRO","cod_reg":"R3"},
    "RICAURTE":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "LA MESA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "LAMESA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "COGUA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "NILO":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "SILVANIA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "VILLAPINZON":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "SAN BERNARDO":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "VIILANUEVA":{"departamento":"CASANARE","zona":"CENTRO","cod_reg":"R3"},
    "MESITAS DEL COLEGIO":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R3"},
    "CARMEN DE APICALA":{"departamento":"TOLIMA","zona":"CENTRO","cod_reg":"R3"},
    "EL ROSAL":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "LA VEGA":{"departamento":"CUNDINAMARCA","zona":"CENTRO","cod_reg":"R4"},
    "IBAGUE":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "ESPINAL":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "MARIQUITA":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "HONDA":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "GUAMO":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "PURIFICACION":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "VENADILLO":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "LERIDA":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "CHAPARRAL":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "MELGAR":{"departamento":"TOLIMA","zona":"CENTRO","cod_reg":"R3"},
    "SALDAÑA":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "LIBANO":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "NATAGAIMA":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "ORTEGA":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "ARMERO GUAYABAL":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "HONDA":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R7"},
    "FRESNO":{"departamento":"TOLIMA","zona":"OCCIDENTE","cod_reg":"R1"},
    "LA DORADA":{"departamento":"CALDAS","zona":"OCCIDENTE","cod_reg":"R7"},
    "SOGAMOSO":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "DUITAMA":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "TUNJA":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "MONIQUIRA":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "VILLA DE LEYVA":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "CHIQUINQUIRA":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "RAMIRIQUI":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "SANTA ROSA DE VITERBO":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "PAIPA":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "NOBSA":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "SAMACA":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "GARAGOA":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "GUATEQUE":{"departamento":"BOYACA","zona":"CENTRO","cod_reg":"R4"},
    "PUERTO BOYACA":{"departamento":"BOYACA","zona":"OCCIDENTE","cod_reg":"R7"},
    "PUERTO TRIUNFO":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "GRANADA":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "SAN MARTIN":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "ACACIAS":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "PUERTO LOPEZ":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "VILLAVICENCIO":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "CUMARAL":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "GUAMAL":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "MESETAS":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "FUENTE DE ORO":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "PUERTO GAITAN":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "PALMIRA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "CALI":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "CALI OLIMPICO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "GINEBRA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "RIOFRIO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "PRADERA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "RESTREPO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "GUACARI":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "EL CERRITO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "YUMBO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "FLORIDA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "YOTOCO":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "JAMUNDI":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "CANDELARIA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "GUADALAJARA DE BUGA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "CALIMA EL DARIEN":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "BUENAVENTURA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "VIJES":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "DAGUA":{"departamento":"VALLE","zona":"OCCIDENTE","cod_reg":"R8"},
    "MONTERIA":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "SAHAGUN":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "CHINU":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "MONTELIBANO":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "CERETE":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "LORICA":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "PLANETA RICA":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "CIENAGA DE ORO":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "SAN ANTERO":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "SAN BERNARDO DEL VIENTO":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "SAN PELAYO":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "TIERRALTA":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "COTORRA":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "MOÑITOS":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "MOMIL":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "PUEBLO NUEVO":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "BUENAVISTA":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "LA APARTADA":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "AYAPEL":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "VALENCIA":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "PUERTO LIBERTADOR":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "SAN ANDRES SOTAVENTO":{"departamento":"CORDOBA","zona":"NORTE","cod_reg":"R6"},
    "BUCARAMANGA":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "BARRANCABERMEJA":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "GIRON":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "BARBOSA":{"departamento":"SANTANDER","zona":"CENTRO","cod_reg":"R4"},
    "FLORIDABLANCA":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "PIEDECUESTA":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "SOCORRO":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "SAN GIL":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "MALAGA":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "SABANA DE TORRES":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "PUERTO WILCHES":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "LEBRIJA":{"departamento":"SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "VILLA DEL ROSARIO":{"departamento":"NORTE SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "CUCUTA":{"departamento":"NORTE SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "LOS PATIOS":{"departamento":"NORTE SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "OCAÑA":{"departamento":"NORTE SANTANDER","zona":"NORTE","cod_reg":"R10"},
    "ABREGO":{"departamento":"NORTE SANTANDER","zona":"NORTE","cod_reg":"R10"},
    "CHINACOTA":{"departamento":"NORTE SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "EL ZULIA":{"departamento":"NORTE SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "PAMPLONA":{"departamento":"NORTE SANTANDER","zona":"NORTE","cod_reg":"R11"},
    "VALLEDUPAR":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "BOSCONIA":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "EL COPEY":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "LA PAZ":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "AGUACHICA":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "CHIRIGUANA":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "PUEBLO BELLO":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "CHIMICHAGUA":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "CURUMANI":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "LA JAGUA DE IBIRICO":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "PELAYA":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "SAN DIEGO":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "BECERRIL":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "PAILITAS":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "EL PASO":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "AGUSTIN CODAZZI":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "ASTREA":{"departamento":"CESAR","zona":"NORTE","cod_reg":"R10"},
    "RIOHACHA":{"departamento":"LA GUAJIRA","zona":"NORTE","cod_reg":"R10"},
    "MAICAO":{"departamento":"LA GUAJIRA","zona":"NORTE","cod_reg":"R10"},
    "BARRANCAS":{"departamento":"LA GUAJIRA","zona":"NORTE","cod_reg":"R10"},
    "FONSECA":{"departamento":"LA GUAJIRA","zona":"NORTE","cod_reg":"R10"},
    "HATONUEVO":{"departamento":"LA GUAJIRA","zona":"NORTE","cod_reg":"R10"},
    "DIBULLA":{"departamento":"LA GUAJIRA","zona":"NORTE","cod_reg":"R10"},
    "SAN JUAN DEL CESAR":{"departamento":"LA GUAJIRA","zona":"NORTE","cod_reg":"R10"},
    "URIBIA":{"departamento":"LA GUAJIRA","zona":"NORTE","cod_reg":"R10"},
    "MANAURE":{"departamento":"LA GUAJIRA","zona":"NORTE","cod_reg":"R10"},
    "ALBANIA":{"departamento":"LA GUAJIRA","zona":"NORTE","cod_reg":"R10"},
    "CAUCASIA":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "ARBOLETES":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "CAREPA":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "TURBO":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "APARTADO":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "CHIGORODO":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "NECOCLI":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "SAN PEDRO DE URABA":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "SAN JUAN DE URABA":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "NECHI":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "TARAZA":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "EL BAGRE":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "ZARAGOZA":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R6"},
    "YONDO":{"departamento":"ANTIOQUIA","zona":"NORTE","cod_reg":"R11"},
    "RIONEGRO":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "MEDELLIN":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "GUARNE":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "JARDIN":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "ITAGUI":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "SONSON":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "ENVIGADO":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "BELLO":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "MARINILLA":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "EL RETIRO":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "RETIRO":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "AMAGA":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "SANTA FE DE ANTIOQUIA":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "VENECIA":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "SAN JERONIMO":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "SABANETA":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "LA ESTRELLA":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "COPACABANA":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "CALDAS":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "SANTA ROSA DE OSOS":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "CARMEN DE VIBORAL":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "SOPETRAN":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "GIRARDOTA":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "YARUMAL":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "TAMESIS":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "FREDONIA":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "LA CEJA":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "ELPEÑOL":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "GUATAPE":{"departamento":"ANTIOQUIA","zona":"ANTIOQUIA","cod_reg":"R9"},
    "NEIVA":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "PITALITO":{"departamento":"HUILA","zona":"CENTRO","cod_reg":"R3"},
    "GARZON":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "LA PLATA":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "GIGANTE":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "RIVERA":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "CAMPOALEGRE":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "TIMANA":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "SAN AGUSTIN":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "AIPE":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "SUAZA":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "GUADALUPE":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "ACEVEDO":{"departamento":"HUILA","zona":"OCCIDENTE","cod_reg":"R7"},
    "POPAYAN":{"departamento":"CAUCA","zona":"OCCIDENTE","cod_reg":"R8"},
    "SANTANDER DE QUILICHAO":{"departamento":"CAUCA","zona":"OCCIDENTE","cod_reg":"R8"},
    "PUERTO TEJADA":{"departamento":"CAUCA","zona":"OCCIDENTE","cod_reg":"R8"},
    "MIRANDA":{"departamento":"CAUCA","zona":"OCCIDENTE","cod_reg":"R8"},
    "PIENDAMO":{"departamento":"CAUCA","zona":"OCCIDENTE","cod_reg":"R8"},
    "TIMBIO":{"departamento":"CAUCA","zona":"OCCIDENTE","cod_reg":"R8"},
    "VILLA RICA":{"departamento":"CAUCA","zona":"OCCIDENTE","cod_reg":"R8"},
    "PASTO":{"departamento":"NARINO","zona":"OCCIDENTE","cod_reg":"R8"},
    "IPIALES":{"departamento":"NARINO","zona":"OCCIDENTE","cod_reg":"R8"},
    "TUQUERRES":{"departamento":"NARINO","zona":"OCCIDENTE","cod_reg":"R8"},
    "TUMACO":{"departamento":"NARINO","zona":"OCCIDENTE","cod_reg":"R8"},
    "SINCELEJO":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "SAN MARCOS":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "SAN ONOFRE":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "COROZAL":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "SAMPUES":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "GALERAS":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "COVEÑAS":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "TOLU":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "MAJAGUAL":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "GUARANDA":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "SAN JUAN DE BETULIA":{"departamento":"SUCRE","zona":"NORTE","cod_reg":"R6"},
    "MOMPOX":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R10"},
    "VILLANUEVA":{"departamento":"BOLIVAR","zona":"NORTE","cod_reg":"R2"},
    "FLORENCIA":{"departamento":"CAQUETA","zona":"OCCIDENTE","cod_reg":"R7"},
    "SAN VICENTE DEL CAGUAN":{"departamento":"CAQUETA","zona":"OCCIDENTE","cod_reg":"R7"},
    "VILLAVICENCIO":{"departamento":"META","zona":"CENTRO","cod_reg":"R3"},
    "YOPAL":{"departamento":"CASANARE","zona":"CENTRO","cod_reg":"R3"},
    "ARAUCA":{"departamento":"ARAUCA","zona":"NORTE","cod_reg":"R11"},
    "SAN JOSE DE GUAVIARE":{"departamento":"GUAVIARE","zona":"CENTRO","cod_reg":"R3"},
    "LETICIA":{"departamento":"AMAZONAS","zona":"OCCIDENTE","cod_reg":"R7"},
    "MOCOA":{"departamento":"PUTUMAYO","zona":"OCCIDENTE","cod_reg":"R7"},
    "PUERTO ASIS":{"departamento":"PUTUMAYO","zona":"OCCIDENTE","cod_reg":"R7"},
    "ORITO":{"departamento":"PUTUMAYO","zona":"OCCIDENTE","cod_reg":"R7"},
    "QUIBDO":{"departamento":"CHOCO","zona":"OCCIDENTE","cod_reg":"R1"},
}


def buscar_ciudad(ciudad_str: str) -> dict | None:
    """Busca una ciudad en el catálogo (case-insensitive, ignora tildes básicas)."""
    if not ciudad_str:
        return None
    normalizada = ciudad_str.upper().strip()
    # Búsqueda exacta
    if normalizada in CIUDADES:
        return CIUDADES[normalizada]
    # Búsqueda parcial — primera coincidencia que contenga el texto
    for key, val in CIUDADES.items():
        if normalizada in key or key in normalizada:
            return {**val, "_ciudad_normalizada": key}
    return None
